update travis.yum
php-xapi/serializer pull request #40
Opened 2018-04-15 18:49 UTC by djoudi

2018-04-15 20:33 UTC, xabbuh requested changes

2018-04-15 20:33 UTC, xabbuh commented on .travis.yml
> +      env: xdebug="yes" COMPOSER_OPTIONS=""
I would not add these to builds. Just using 7.1 and 7.2 without Xdebug is enough.

2018-04-15 20:33 UTC, xabbuh commented on .travis.yml
> +  - 7.0
PHP 7.0 is already covered below

2018-04-16 09:06 UTC, xabbuh requested changes

2018-04-16 09:06 UTC, xabbuh commented on .travis.yml
> -  - 5.4
Please keep the existing build jobs for now. I will consider which PHP versions I want to support during the next days. But as long as the Composer constraints do not limit the usable PHP versions I do not want to not test them anymore.

2018-04-16 09:06 UTC, xabbuh commented on composer.json
> +        "php-xapi/model": "^1.0 || ^2.0 || 3.0",
This line should be `"php-xapi/model": "^1.1.1 || ^2.0.1 || 3.0",`.

2018-04-16 09:49 UTC, djoudi commented
Fatal error: Cannot use 'Object' as class name as it is reserved in /home/travis/build/php-xapi/serializer/vendor/php-xapi/model/src/Object.php on line 19

2018-04-18 19:07 UTC, xabbuh commented
Thank you for this PR @djoudi. I have fixed this together with #41 after making some releases in other packages in #43.

2018-04-18 19:07 UTC, closed without merging